-- In-flight OIDC authorization requests.
--
-- One row per started login, consumed by the callback and deleted in the same
-- statement so a code can only be redeemed once. Rows are short-lived (minutes);
-- `expires_at` is swept by a background prune and also enforced on read, so a
-- prune that has not run yet cannot resurrect an expired login.
--
-- `state` is the value sent to the identity provider. It is generated by the
-- server from a CSPRNG and never derived from anything the caller supplies.
CREATE TABLE IF NOT EXISTS oidc_login_states (
    state         TEXT        PRIMARY KEY,
    provider      TEXT        NOT NULL,
    code_verifier TEXT        NOT NULL,
    nonce         TEXT        NOT NULL,
    spa_state     TEXT        NOT NULL,
    expires_at    TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_oidc_login_states_expires_at
    ON oidc_login_states (expires_at);
