pub mod sso;

pub use sso::{
    list_oidc_providers, oidc_callback, oidc_login, oidc_refresh, OidcProviderInfo, RefreshRequest,
    RefreshResponse,
};

use serde::Deserialize;

// ── Shared query / request types ──────────────────────────────────────────────

#[derive(Deserialize)]
pub struct LoginQuery {
    /// CSRF state generated by the frontend (stored in sessionStorage).
    /// Omit to probe whether OIDC is configured (returns 200 when available).
    pub state: Option<String>,
    /// Provider name to log in with. Defaults to the first configured provider.
    pub provider: Option<String>,
}

#[derive(Deserialize)]
pub struct CallbackQuery {
    pub code: Option<String>,
    pub state: Option<String>,
    pub error: Option<String>,
    pub error_description: Option<String>,
}

// ── Helpers ────────────────────────────────────────────────────────────────────

pub(super) fn spa_error_redirect(base: &str, msg: &str) -> actix_web::HttpResponse {
    actix_web::HttpResponse::Found()
        .insert_header((
            "Location",
            format!("{base}/?oidc_error={}", url_encode(msg)),
        ))
        .finish()
}

/// Split `"<provider>:<user_state>"` into `("<provider>", "<user_state>")`.
/// Falls back to `("", raw)` for states that have no provider prefix (e.g. legacy).
pub(super) fn split_combined_state(raw: &str) -> (&str, &str) {
    match raw.find(':') {
        Some(pos) => (&raw[..pos], &raw[pos + 1..]),
        None => ("", raw),
    }
}

pub(super) fn url_encode(s: &str) -> String {
    s.chars()
        .flat_map(|c| {
            if c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.' | '~') {
                vec![c]
            } else {
                c.to_string()
                    .bytes()
                    .flat_map(|b| format!("%{b:02X}").chars().collect::<Vec<_>>())
                    .collect()
            }
        })
        .collect()
}
