pub mod sso;

pub use sso::{
    list_oidc_providers, oidc_callback, oidc_login, oidc_refresh, OidcProviderInfo,
    RefreshRateLimiter, RefreshRequest, RefreshResponse,
};

use serde::Deserialize;

// ── Shared query / request types ──────────────────────────────────────────────

#[derive(Deserialize)]
pub struct LoginQuery {
    /// CSRF state generated by the frontend (stored in sessionStorage).
    /// Omit to probe whether OIDC is configured (returns 200 when available).
    pub state: Option<String>,
    /// Provider name to log in with. Defaults to the first configured provider.
    pub provider: Option<String>,
}

#[derive(Deserialize)]
pub struct CallbackQuery {
    pub code: Option<String>,
    pub state: Option<String>,
    pub error: Option<String>,
    pub error_description: Option<String>,
}

// ── Helpers ────────────────────────────────────────────────────────────────────

pub(super) fn spa_error_redirect(base: &str, msg: &str) -> actix_web::HttpResponse {
    actix_web::HttpResponse::Found()
        .insert_header((
            "Location",
            format!("{base}/?oidc_error={}", url_encode(msg)),
        ))
        .finish()
}

// `split_combined_state` lived here: the callback used to read the provider name
// out of the `state` it was handed, then fall back to the first configured flow
// when the prefix matched nothing — so a code could be presented for redemption
// at a token endpoint of the caller's choosing. The provider now comes from the
// server-side `LoginState`, and the state is an opaque handle with no structure
// to parse.

pub(super) fn url_encode(s: &str) -> String {
    s.chars()
        .flat_map(|c| {
            if c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.' | '~') {
                vec![c]
            } else {
                c.to_string()
                    .bytes()
                    .flat_map(|b| format!("%{b:02X}").chars().collect::<Vec<_>>())
                    .collect()
            }
        })
        .collect()
}
