[tools]
claude = "latest"
cocogitto = "latest"
go = "latest"
helm = "latest"
k6 = "latest"
lazydocker = "latest"
mc = "latest"
node = "24"
rust = "latest"
task = "latest"
#"github:batleforc/batlehub" = { version = "latest", asset_pattern = "batlehub-cli-*" }
