name: Publish
on:
  push:
    branches:
      - main
    paths:
      - website/**
      - .forgejo/workflows/website.yaml
  workflow_dispatch:

jobs:
  publish:
    runs-on: git-pages
    name: Publish batlehub website
    enable-openid-connect: true # Required for vault authentication
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Build website
        run: |
          cd website
          yarn install
          yarn run docs:build
          cp -R .vitepress/dist ../dist
          cd ..
          ls -la dist
      - name: Publish to Git Pages
        run: |
          git-pages-cli https://${{ github.repository_owner }}.git.batleforc.fr/batlehub --token ${{ secrets.GITHUB_TOKEN }} --upload-dir dist
