{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "batlehub.fullname" . }}-config
  labels:
    {{- include "batlehub.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.toml: |
    {{- include "batlehub.config" . | nindent 4 }}
{{- end }}
